const IndianStatesList = [
  { label: "Andhra Pradesh", tin: "37", code: "AD" },
  { label: "Arunachal Pradesh", tin: "12", code: "AR" },
  { label: "Assam", tin: "18", code: "AS" },
  { label: "Bihar", tin: "10", code: "BR" },
  { label: "Chattisgarh", tin: "22", code: "CG" },
  { label: "Delhi", tin: "7", code: "DL" },
  { label: "Goa", tin: "30", code: "GA" },
  { label: "Gujarat", tin: "24", code: "GJ" },
  { label: "Haryana", tin: "6", code: "HR" },
  { label: "Himachal Pradesh", tin: "2", code: "HP" },
  { label: "Jammu and Kashmir", tin: "1", code: "JK" },
  { label: "Jharkhand", tin: "20", code: "JH" },
  { label: "Karnataka", tin: "29", code: "KA" },
  { label: "Kerala", tin: "32", code: "KL" },
  { label: "Lakshadweep Islands", tin: "31", code: "LD" },
  { label: "Madhya Pradesh", tin: "23", code: "MP" },
  { label: "Maharashtra", tin: "27", code: "MH" },
  { label: "Manipur", tin: "14", code: "MN" },
  { label: "Meghalaya", tin: "17", code: "ML" },
  { label: "Mizoram", tin: "15", code: "MZ" },
  { label: "Nagaland", tin: "13", code: "NL" },
  { label: "Odisha", tin: "21", code: "OD" },
  { label: "Pondicherry", tin: "34", code: "PY" },
  { label: "Punjab", tin: "3", code: "PB" },
  { label: "Rajasthan", tin: "8", code: "RJ" },
  { label: "Sikkim", tin: "11", code: "SK" },
  { label: "Tamil Nadu", tin: "33", code: "TN" },
  { label: "Telangana", tin: "36", code: "TS" },
  { label: "Tripura", tin: "16", code: "TR" },
  { label: "Uttar Pradesh", tin: "9", code: "UP" },
  { label: "Uttarakhand", tin: "5", code: "UK" },
  { label: "West Bengal", tin: "19", code: "WB" },
  { label: "Andaman and Nicobar Islands", tin: "35", code: "AN" },
  { label: "Chandigarh", tin: "4", code: "CH" },
  { label: "Dadra & Nagar Haveli and Daman & Diu", tin: "26", code: "DNHDD" },
  { label: "Ladakh", tin: "38", code: "LA" },
  { label: "Other Territory", tin: "97", code: "OT" },
];

export default IndianStatesList;
